# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HBV <- function(date, streamflow) {
    .Call(`_wateRTools_HBV`, date, streamflow)
}

degree_day <- function(x) {
    .Call(`_wateRTools_degree_day`, x)
}

sacsma <- function(parameters, objective, precipitation, pet) {
    .Call(`_wateRTools_sacsma`, parameters, objective, precipitation, pet)
}

CFD <- function(x) {
    .Call(`_wateRTools_CFD`, x)
}

FD0 <- function(x) {
    .Call(`_wateRTools_FD0`, x)
}

SU25 <- function(x) {
    .Call(`_wateRTools_SU25`, x)
}

ID0 <- function(x) {
    .Call(`_wateRTools_ID0`, x)
}

TR20 <- function(x) {
    .Call(`_wateRTools_TR20`, x)
}

WD <- function(x) {
    .Call(`_wateRTools_WD`, x)
}

TXx <- function(x) {
    .Call(`_wateRTools_TXx`, x)
}

RX1day <- function(x) {
    .Call(`_wateRTools_RX1day`, x)
}

RX5day <- function(x) {
    .Call(`_wateRTools_RX5day`, x)
}

PRCPTOT <- function(x) {
    .Call(`_wateRTools_PRCPTOT`, x)
}

